### ISSUE TITLE
RE: Failure to install on ubuntu 22.04

### ISSUE THREAD

**Issue by wayneoutthere** [qzind/qz.sh#1]
Hello
I'm trying to install but it fails on pre-install task.  I"m on ubuntu 22.04, thanks:
---------------
```
DEBUG=true wget -O - qz.sh |bash
--2022-10-07 11:20:20--  http://qz.sh/
Resolving qz.sh (qz.sh)... 185.199.108.153, 185.199.111.153, 185.199.109.153, ...
Connecting to qz.sh (qz.sh)|185.199.108.153|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6670 (6.5K) [text/html]
Saving to: ‘STDOUT’

-                   100%[===================>]   6.51K  --.-KB/s    in 0s      

2022-10-07 11:20:20 (13.2 MB/s) - written to stdout [6670/6670]

Parsing https://api.github.com/repos/qzind/tray/releases?per_page=100...
Latest stable version found: v2.1.6
Searching .run downloads for v2.1.6 matching amd64...
Downloading https://github.com/qzind/tray/releases/download/v2.1.6/qz-tray-2.1.6%2B3.run...
Download successful, beginning the install...
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing QZ Tray Installer  100%  
Starting install...

Running preinstall task...
      [failure] Task preinstall failed.

Re-run with DEBUG=true for more information.
```

**Comment by tresf** [comment]
This usually means you're missing Java (`openjdk`)... instead of installing that, want to try out the beta, it has Java included:
```bash
wget -O - qz.sh |bash -s -- "beta"

# or if you prefer curl:
# curl qz.sh |bash -s -- "beta" 
```

**Comment by wayneoutthere** [comment]
this seems to work well, thanks very much.
The only thing is... how to use QZ tray, haha.  This is my next adventure... thanks for quick response.

**Comment by tresf** [comment]
> this seems to work well, thanks very much. The only thing is... how to use QZ tray, haha. This is my next adventure... thanks for quick response.

😅 https://www.youtube.com/watch?v=wKIY4gqkIFE

**Comment by wayneoutthere** [comment]
wow. awesome.  except I have to review JS and HTML to print a page, haha.  Oh boy.. nice work though this looks really cool

**Comment by tresf** [comment]
> wow. awesome. except I have to review JS and HTML to print a page, haha. Oh boy.. nice work though this looks really cool

Yeah, it's a client-side (browser) API, so it does require JavaScript.
